# Generated by Django 3.2.7 on 2021-10-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0003_remove_producto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='', max_length=150),
        ),
    ]
